# -*- coding: utf-8 -*-
"""aprendendo while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9ilfo16raioK3T6ZI5iuxywR11_lgLZ
"""

s=1000

while s < 5000:
  s+=1000

  print(f" o salario ainda é R$ {s}")

n = 1
while n<=10:
  print(n)
  n +=1

n=int ( input("fale um numero para contar"))
while n >=0:
  print(n)
  n-=1

import getpass
s=(input("fale uma senha"))
while s != '1234':
  print("tente novamente")
  s=getpass.getpass("fale uma senha: ")
print("acesso permitido")

soma = 0
n= int(input("fale um numero ou 0 para sair! "))
while n != 0:
  soma+= n
  n= int(input("fale um numero ou 0 para sair! "))
print(f"soma total= {soma}")

n=int(input("fale um num positivo"))
while n < 0:
  print(f" {n} é invalido")
  print(" tente novamente")
  n=int(input("fale um num positivo"))
tabuda= 1
while tabuda <=10:
  resultado= n*tabuda
  print(f"{n}x{tabuda}= {resultado}")
  tabuda+=1

import random
n= random.randint(1,10)
resultado=int(input("fale um numero e tente acertar:"))
while resultado!=n:
  print("ERROU!")
  resultado=int(input("fale um numero e tente acertar"))
print('ACERTOU')

soma=0
contador=0

nota= float(input("digite uma nota ou -1 para sair"))
while nota != -1:
  soma+=nota
  contador+=1
  nota= float(input("digite uma nota ou -1 para sair"))
if contador >0:
  media= soma/contador
  print(f"media das notas: {media}")
else:
  print("nenhuma nota foi digitada")

n=int(input("fale um numero"))
contador= 0

while contador<=n:
  if contador%2 ==0:
    print(contador)
  contador+=1

total=0
saque=float(input("fale um valor ou 0 para sair"))
while saque !=0:
  if saque > 0:
    print(f"saque de R$ {saque} realizado")
  else:
    print(f"valor invalido")
  saque=float(input("fale um valor ou 0 para sair"))
print("operação encerrada!")

maior=0
idade=int(input("fale sua idade: ou digite um numero negativo para sair "))
while idade >= 0:
  if idade >=18:
    maior+=1
  idade=int(input("fale sua idade: "))
print(f"total de passoas maiores de idade são: {maior}")

while True:
  print("esse laço é infinito")

total=0
saldo=int(input("fale um valor que quer sacar ou digite 0 para sair "))

while saldo!=0:
  if saldo>0:
    total+=saldo
  saldo=int(input("fale um valor que quer sacar ou digite 0 para sair "))
print(f"seu saque foi de {total}")
print("finalizado")