# -*- coding: utf-8 -*-
"""aula 04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvkiLAjg7ng-zo96QVEVpMAJMnY5b-E4
"""

for cont in range(1,5):
  valor= int(input("fale um numero! "))
  multi=(valor * 12)
  print(multi)

for cont in range(4):
  x=int(input("fale um numero: "))
  y=int(input("fale outro numero: "))
  total=(x*y)
  print(total)

for cont in range(1,11):
  print(cont)

for multi in range(0,11):
  total= (5*multi)
  print(f"5 x {multi} = {total}")

soma=0

for i in range( 1,100):
  soma = 1
  print(f"soma de 1 a 100= {soma}")

print("os numeros pares são: ")
for par in range(0,21,2):
  print(f"- {par}")

for name in range(1,5):
  nome=(input("qual é o seu nome? "))
  print(f"vc se chama {nome}")

for n in range(10,0,-1):
  print(n)

for cont in range(1,11):

  print(f"{cont}² = {cont**2}")

soma = 0
for media in range(5):
  nota1=int(input("fale sua nota: "))
  soma += nota1
total= soma/5
print(f"sua media é {total}")

numero= int(input("fale um numero: "))
divisor= 0
for contador in range(1, numero +1):
  if numero % contador == 0:
    divisor += 1
if divisor==2:
  print("é primo")
else:
  print("não é primo")

for mult in range(1,30):
  if mult % 3 == 0:
    print(mult)