# -*- coding: utf-8 -*-
"""exercicios do senai

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCvqNrMNh3qv-PiKd5V0-Li-Y8yIh5aM

exercicio1
"""

x=7
y=10

soma= x+y

print(soma)

"""exercicio 2

"""

numero1=float(input("Fale algum numero por favor!"))

if numero1>0:
  print(f"O numero {numero1:.0f} é positivo")
elif numero1==0:
  print(f"O numero {numero1:.0f} é neutro")
else:
  print(f"Esse numero {numero1:.0f} é negativo")

"""exercicio 3"""

idade=int(input("Qual é a sua idade?"))

if idade>=18:
  print(f"voce tem {idade} anos, então voce é maior de idade!")
elif idade<18:
  print(f"voce tem {idade} anos, então voce é menor de idade!")

"""exercicio 4"""

temperatura=float(input("hoje esta com quantas Graus?"))

if temperatura>25:
  print(f"Hoje esta com {temperatura:.0f} graus, então esta calor")
elif temperatura>20:
  print(f"Hoje esta com {temperatura:.0f} graus, então esta neutro")
else:
  print(f"Hoje esta com {temperatura:.0f} graus, então esta frio")

"""exercicio 5

"""

numero1= int(input("Fale algum numero, por favor."))
numero2= int(input("Fal outro numero agora."))

if numero1==numero2:
  print("Esses numeros não são diferentes")
elif numero1!=numero2:
  print("Esses numero são diferentes")

"""exercicio 6

"""

senha= int(input("Precisamos saber sua senha, pode digitar para podermos verificar por favor."))
senha==1234:
if senha==1234:
  print("ACESSO PERMITIDO , Muito obrigado,sua senha esta correta")
elif senha!=1234:
  print(f"ACESSO NEGADO, sua senha {senha} esta INCORRETA")

"""exercicio 7

"""

nota1= int(input("Quanto voce tirou?"))
nota2= int(input("Quanto voce tirou?"))
media= (nota1+nota2)/2

if media>7:
  print(f"PARABÉS!! Sua media foi {media}, voce esta aprovado!")
elif media>5:
  print(f"Foque mais um pouco, sua media foi {media}, voce está de recuperação!")
else:
  print(f"Voce está REPROVADO, sua media foi {media}.")

"""exercicio 8"""

primeirotime=(input( "Fale o nome de um time que está jogando? ") )
segundotime= (input( "Qual é o outro time? ") )

placartime1= int(input(f"quanto esta para o {primeirotime}?"))
placartime2= int(input(f"quanto esta para o {segundotime}?"))

if placartime1>placartime2:
  print(f"o {primeirotime} esta ganhando!")
elif placartime1<placartime2:
  print(f" o {segundotime} esta ganhando!")
else:
  print("o jogo esta empatado!")