# -*- coding: utf-8 -*-
"""exercicios senai 2pt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QfYr1JGAhq5_gQozc0ztQVl7t0OBobQe

exercicio 9
"""

periodo1=(input("qual periodo voce estuda"))
if periodo1=="de tarde":
  print("BOA TARDE")
elif periodo1=="de manha":
  print("BOM DIA")
elif periodo1=="de noite":
  print("BOA NOITE")
else: print("VALOR INVALIDO")

"""exercicio 10"""

idade= int(input("Qual é a s sua idade?"))

if idade<=11:
  print(f"voce tem {idade}, voce é criança!")
elif idade<=18:
  print(f"voce tem {idade}, voce é adolecente!")
elif idade<=24:
  print(f"voce tem {idade}, voce é jovem!")
elif idade<40:
  print(f"voce tem {idade}, voce é adulto!")
elif idade<=60:
  print(f"voce tem {idade}, voce é meia idade!")
else:
  print("voce é idosa!")

"""exercicio 11"""

salario= int(input("Qual é o valor do seu salario?"))

aumento=(salario * 20/100)
aumento1=(salario * 15)
aumento2=(salario * 10/100)
aumento3=(salario * 5/100)

if salario<=280:
  print("voce receu um aumento de 20%")
  print(f"o seu salario teve um acrescento de R$ {salario * 20/100 :.2f}")
  print(f"o seu salario agora é de R$ {aumento + salario :.2f}")

if salario<=700:
  print("voce recebeu um aumento de 15%")
  print(f" o seu salario teve um acrescento de R% {salario * 15/100 :.2f}")
  print(f" o seu salrio agora é de {salario*aumento1 :.2f}")
if salario<1500:
  print("voce recebeu um aumento de 10%")
  print(f" o seu salario teve um acrescento de R% {salario * 10/100 :.2f}")
  print(f" o seu salrio agora é de {salario*aumento2 :.2f}")
else:
  print("voce recebeu um aumento de 5%")
  print(f" o seu salario teve um acrescento de R% {salario * 5/100 :.2f}")
  print(f" o seu salrio agora é de {salario*aumento3 :.2f}")

"""exercicio 12"""

dia=int(input("digite um numero"))

if dia==1:
  print(f"hoje é domingo")
elif dia==2:
  print("hoje é segunda feira")
elif dia==3:
  print("hoje é terça feira")
elif dia==4:
  print("hoje é quarta feira")
elif dia==5:
  print("hoje é quinta feira")
elif dia==6:
  print("hoje é sexta feira")
elif dia==7:
  print("hoje é sabado feira")

"""exercicio 13"""

temperatura=int(input(""" VOU FAZER UM TESTE DE CONVERSÃO:

1-converter fahrenheit para Celsius

2-converter Celsius para Fahrenheit?

ESCOLHA UMA DAS OPCÕES-->"""))

graus=int(input("QUANTPS GRAUS ESTA HOJE?"))

if temperatura==1:
  celsius= (graus - 32) * 5/9
  print(f"hoje esta {celsius} c")
else:
  fahrenheit= (graus * 9/5) + 32
  print(f"hoje esta {fahrenheit} f")

"""EXERCICIO 14"""

print(""""
Estamos nos preparando para as eleições!!

 A baixo esta a tabela das idades que precisam votar:

Pessoas com idade menor que 16 anos são proibidas de votar (proibido);
 Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar
(optativo);
 Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar
(obrigatório);
 Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo).
""")
idade= int(input("Qual é a sua idade?"))

if idade<16:
  print(f"voce tem {idade} anos, voce esta proibida de votar!")
elif idade<18:
  print(f"voce tvem {idade}anos, voce é uma optativo para votar!")

elif idade<65:
  print(f"voce tem { idade} anos, o seu voto é obrigatorio!")
else:
  print(f"voce tem {idade} anos,voce é uma optativo para votar!")

"""exercicio 15"""

print("""
ESTAMOS INVESTIGANDO UM CRIME.

Vou precisar fazer algumas perguntas pra voce!
""")
resposta=(input("consegue me ajudar?"))

if resposta=="sim":


  print("Certo, então vamos la!")
else:

  print("voce é obrigado a me reponder, então vamos la!")

telefonou=(input(" por acaso voce telefonou para a vítima em algum momento?"))

if telefonou=="sim":

  print("ok")
elif telefonou=="não":

  print("ok")
else:

  print("preciso de uma resposta concreta!")

local=(input("voce esta no local do crime na hora que ela morreu? "))
if local=="sim":

  print("nao acredito!")

  resposta=(input("voce viu a vitima em algum momento?"))
  if resposta=="sim":

    print("depois vou precisar fazer algumas perguntas pra voce sobre isso então!")
  elif resposta=="não":

    print("ok Então!")
  else:

    print("é melhors passar-mos para a proxima pergunta! ")

elif local=="não":

  print("certo")
else:

  print("preciso que voce me de uma resposta completa!")

mora=(input("voce mora perto da vitima?"))

if mora=="sim":

  print("certo!")
  casa=(input("aonde voce mora então?"))

  if casa=="no final da rua dela":
    print("mas mesmo nessa distancia não daria para voce ter visto nada de estranho.")


elif mora=="não":

  print("certo, então")
else:
  print("PRECISO DE UMA RESPOSTA CONCRETA!"
  )

dever=(input("voce devia alguma coisa para a vitima?"))
if dever=="sim":

  print("eita!")
elif dever=="não":
  print("PERFEITO!")
else:
  print("PRECISO DE UMA RESPOSTA CONCRETA!")

trabalhar=(input("voce já trabalhou com a vitima??"))

if trabalhar=="sim":
  print("Certo, vou anotar isso!")
elif trabalhar=="não":
  print("Ok então, vou dar uma olhada aqui nas minhas anotaçoes e ja te libero")
else:
  print("PRECISO DE UMA RESPOSTA CONCRETA")

print("Aguarde um pouco que ja volto para te dar a respostas!")

respostas1=0


telefonou=(input(" por acaso voce telefonou para a vítima em algum momento?"))

if telefonou=="sim":
  respostas1+=1

elif telefonou=="não":

  print("ok")
else:

  print("preciso de uma resposta concreta!")

local=(input("voce esta no local do crime na hora que ela morreu? "))
if local=="sim":
  respostas1+=1

elif local=="não":

  print("certo")
else:

  print("preciso que voce me de uma resposta completa!")

mora=(input("voce mora perto da vitima?"))

if mora=="sim":
    respostas1+=1

elif mora=="não":

  print("certo, então")
else:
  print("PRECISO DE UMA RESPOSTA CONCRETA!")

dever=(input("voce devia alguma coisa para a vitima?"))
if dever=="sim":
  respostas1+=1
elif dever=="não":
  print("PERFEITO!")
else:
  print("PRECISO DE UMA RESPOSTA CONCRETA!")

trabalhar=(input("voce já trabalhou com a vitima??"))

if trabalhar=="sim":
  respostas1+=1


else:
  print("PRECISO DE UMA RESPOSTA CONCRETA")
if respostas1<=1:
  print("inocente")
elif respostas1==2:
  print("Suspeito!")
elif respostas1==3 and 4:
  print("cumplice")
else:
  print("ASSASINO")

"""exercicio 17"""

preço1=int(input("Qual é o valor do produto?"))
preço2=int(input("Qual é o valor do produto?"))
preço3=int(input("Qual é o valor do produto?"))

if preço1<preço2 and preço1<preço3:
  barato=preço1
  produto='salgado'
elif preço2<preço1 and preço2<preço3:
  barato=preço2
  produto='salgadinho'
else:
  barato=preço3
  produto='esfirra'

print(f"o produto mais barato é o {produto}, que custa R$ {barato}")