# -*- coding: utf-8 -*-
"""lista de exercicio pt6- match e case

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bajzIyWNdNB7hKdWuFYqGfLjaATJO_We

EXERCICIO 1
"""

idade=int(input("qual é a sua idade? "))

match idade:
  case idade if 0 <= idade <=12:
    print("voce é uma criança ")
  case idade if 13 <= idade <=17:
   print("voce é um adolecente ")
  case idade if 18<= idade <=59:
    print("voce é um adulto")
  case idade if idade >= 60:
    print("voce ja esta com o pé na cova")

"""EXERCICIO 2"""

nota=int(input("digite sua nota: "))

match nota:
  case nota if 90 <= nota <=100:
    print("voce é um aluno nota A")
  case nota if 80<= nota <=89:
    print("voce é um aluno nota B")
  case nota if 70<= nota <=79:
    print("voce é um aluno nota C")
  case nota if 60<= nota <= 69:
    print("voce é um aluno nota D")
  case nota if nota <60:
    print("voce é um aluno nota F")

"""EXERCICIO 3"""

valor=int(input("qual é o valor do seu produto? R$ "))
cliente=int(input("""
qual cliente voce é?
1-comum- 5%
2-fidelidade- 10%
3-vip- 20%
"""))

match cliente:
  case 1:
    print(f"voce ganhou 5% de desconto no seu produto")
    print(f" o seu desconto é de : R${valor*0.05}")
    print(f"o valor total é: R${valor-(valor*0.05)}")
  case 2:
    print(f"voce ganhou 10% de desconto no seu produto")
    print(f" o seu desconto é de : R${valor*0.1}")
    print(f"o valor total é: R${valor-(valor*0.1)}")
  case 3:
    print(f"voce ganhou 20% de desconto no seu produto")
    print(f" o seu desconto é de : R${valor*0.2}")
    print(f"o valor total é: R${valor-(valor*0.2)}")

"""EXERCICIO 4"""

temperatura=int(input("quatos gruas esta? "))
unidade=int(input("""
deseja converter para qual unidade
1-Celsius para Fahrenheit
2-Fahrenheit para Celsius
"""))

match unidade:
  case 1:
    print(f" de Celsius para Fahrenheit fica: {(temperatura*1.8)+32}F ")
  case 2:
    print(f"de Fahrenheit para Celsius fica:{(temperatura-32)*5/9}C")

"""exercicio 5"""

palavra=(input("fale uma palavra no singular ou no plural "))
match palavra[-1]:
  case "s":
    print("essa palava esta no plural")
  case _:
    print("essa palvra esta no singular")

"""exercicio 6"""

cor=(input("fale um cor em ingles: "))

match cor:
  case "blue":
    print("azul")
  case "pink":
    print("rosa")
  case "black":
    print("preto")
  case "purple":
    print("roxo")
  case "green":
    print("verde")
  case "orange":
    print("laranja")
  case "white":
   print("branco")
  case "gray":
    print("cinza")
  case "brown":
    print("marrom")
  case "yellow":
    print("amarelo")
  case "red":
    print("vermelho")
  case _:
    print("essa cor eu nao sei! ")

"""exercicio 7"""

envio=int(input("""
fale um tipo de envio
1-normal
2-expresso
3-sedex
"""))

match envio:
  case 1:
    print("esse envio demora 15 dias ulteis")
  case 2:
    print("esse envio demora 7 dias ulteis")
  case 3:
    print("esse envio demora 2 dias ulteis")
  case _:
    print("esse envio não esta disponivel no momneto!!")

"""exercicio 8"""

from typing import Match
saque=int(input("""
ESCOLHA ALGUMA OPÇÃO:
1-SALDO
2-SAQUE
3-DEPOSITO
"""))

match saque:
  case 1:
    print("voce escolheu a opção saldo")
    saldo=int(input("qual é o valor do seu saldo: R$"))
    print(f"seu saldo é de {saldo}")
  case 2:
    print("voce escolheu a opção saque")
    saque=int(input("qual é o valor que voce deseja sacar? R$ "))
    print(f"voce sacou: R${saque}")
  case 3 :
    print("voce escolheu a opção deposito")
    deposito=int(input("qual é p valor do deposito que voce gostaria de fazer ? "))
    print(f"voce fez um deposito de: R${deposito}")
  case _:
    print("ERRO, TENTE NOVAMENTE")

"""exercicio 9"""

turno=int(input("""
TURNOS:
1- MATUTINO
2- VESPERITINO
3- NOTURNO
"""))

match turno:
  case 1:
    print("Bom dia, seja bem vindo!")
  case 2:
    print("Boa tarde, seja bem vindo! ")
  case 3:
    print("Boa noite, seja bem vindo")

"""exercicio 10

"""

peso=float(input("qual é o seu peso? "))

match peso:
  case peso if peso<18.5:
    print("voce é abaixo do peso")
  case peso if 18.5<= peso <=24.9:
    print("voce é esta com o peso normal ")
  case peso if 25<= peso <=29.9:
    print("voce esta com sobrepeso ")
  case peso if peso >30:
    print("voce esta acima do peso ")

"""exercicio 11"""

moeda=int(input("""
qual é a moeda que voce deseja converter seus reais?

1-Dolar
2-Euro
3-Libra

"""))
valor=int(input("qual é o valor que deseja converter? R$ "))
match moeda:
  case 1:
    print(f"voce escolheu converter para Dolar")
    print(f" voce tem: ${valor / 5.56:.2f}")
  case 2:
    print(f"voce escolheu converter para Euro")
    print(f" voce tem: €{valor / 6.45:.2f}")
  case 3:
    print(f"voce escolheu converter para Libra")
    print(f" voce tem: £{valor / 7.45:.2f}")
  case _:
    print("não trabalhamos com esse tipo de moeda! ")

"""exercicio 12"""

menu=int(input("""
escolha alguma das opções:
1- iniciar
2- carregar
3- credito
4- sair

"""))

match menu:
  case 1:
    print("jogo iniciando...")
  case 2:
    print("jogo carregando... ")
  case 3:
    print("creditos do jogo")
  case 3:
    print("saindo do jogo...")
  case _:
    print("Não entendi o que voce quis dizer com isso! ")

"""exercico 13"""

arquivo=int(input("""
Qual tipo de aquivo gostaria de escolher?

1-TXT
2-JPG
3-PY

"""))

match arquivo:
  case 1:
    print("o seu tipo de arquivo é texto")
  case 2:
    print("o seu tipo de arquivo é imagem ")
  case 3:
    print("o seu tipo de arquivo é codigo")

"""exercicio 14"""

alerta=(input("""
Qual é o nivel de alerta?

-VERDE
-AMARELO
-VERMELHO
""")).lower()
match alerta:
  case "verde":
    print("esta tudo normal")
  case "amarelo":
    print("Atenção!! Pode acontecer alguma coisa!")
  case "vermelho":
    print("PERIGOO!! TOME CUIDADO")

"""exercico 15"""

dia=input("fale um dia da semana: ").lower()

match dia:
  case "segunda"|"terça"|"quarta"|"quinta"|"sexta":
    print(f"{dia} é um dia ultil")
  case "sababado"|"domingo":
    print(f"{dia} é final de semana")

"""exercicio 16"""

usuario=int(input("""
Qual é o tipo de ajuda que voce precisa?
1-Suporte
2-Vendas
3-Reclamações
"""))
match usuario:
  case 1:
    print("vou te dar o suporte necessario")
  case 2:
    print(" vou te ajudar a vender")
  case 3:
    print("qual é a reclamação que voce deseja fazer?")
    reclamacao=input("")
    print("ok, vou ver o que consigo fazer")

"""exercicio 17"""

idade=int(input("qual é a sua idade? "))
match idade:
  case idade if 0<=idade<=2:
    print(f" voce tem {idade} anos, voce é um bebe!")
  case idade if 3<=idade<=12:
    print(f" voce tem {idade} anos, voce é uma criança!")
  case idade if 13<=idade<=17:
    print(f" voce tem {idade} anos, voce é um adolescente!")
  case idade if 18<=idade<=59:
    print(f" voce tem {idade}, voce é um adulto!")
  case idade if idade>=60:
    print(f" voce tem {idade} anos, voce é um idoso!")

"""exercicio 18"""

produto=input("""
qual é o tipo do seu produto
-Alimento
-Bbebida
-Eletronico

""").lower()

match produto:
  case "alimento":
    print("esse produto tem 10% de imposto")
  case "bebida":
    print("esse produto tem 15% de imposto")
  case "eletronico":
    print("esse produto tem 20% de imposto")

"""exercicio 19"""

conversao=int(input("""
Vamos fazer algumas conersão, qual voce escolhe:
1-km para mi
2-Celsius para Fahrenheit
3-kg para lb

"""))

match conversao:
  case 1:
    km=int(input("quantos km deseja converter? "))
    print(f"km para mi fica: {km/1.6}mi")
  case 2 :
    temperatura=int(input("qual é o grau que deseja converter? "))
    print(f"Celsius para Fahrenheit fica: {(temperatura*1.8)+32}F ")
  case 3:
    kg=int(input("qual é o peso que deseja converter? "))
    print(f"kg para lb fica: {kg*2.2 :.2f}ib")

"""exercicio 20"""

operação= int(input("""
qual é a operação que voce deseja aprender?
1- and
2- or
3- not
"""))

match operação:
  case 1 :
    print("\nA operação 'and' retorna True se AMBAS as condições forem verdadeiras.")
    print("Exemplo:")
    print("True and True é:", True and True)
    print("True and False é:", True and False)
    print("False and True é:", False and True)
    print("False and False é:", False and False)
  case 2:
    print("\nA operação 'or' retorna True se PELO MENOS UMA das condições for verdadeira.")
    print("Exemplo:")
    print("True or True é:", True or True)
    print("True or False é:", True or False)
    print("False or True é:", False or True)
    print("False or False é:", False or False)
  case 3:
    print("\nA operação 'not' inverte o valor booleano de uma condição.")
    print("Exemplo:")
    print("not True é:", not True)
    print("not False é:", not False)
  case _:
    print("essa operação não vou poder te ensinar ")

while True:
     cadastro=int(input("""
     Sistema de Cadastro e Gerenciamento de Notas Escolares:

     O que deseja fazer?
     1. Cadastrar novo aluno
     2. Lançar notas
     3. Ver boletim de um aluno
     4. Listar todos os alunos cadastrados
     5. Encerrar o sistema

     """))
     if cadastro==5:
         break
     match cadastro:
         case 1:
             nome=input("Digite o nome do aluno: ")
             idade=int(input("Digite a idade do aluno: "))
             telefone=int(input("Digite o telefone do aluno: "))

         case 2:
             nome=input("Digite o nome do aluno que deseja ver a nota: ")
             for notas in range(1,5):
                 nota=input(f"Digite a {notas}° nota do aluno: ")