# -*- coding: utf-8 -*-
"""lista de exercicio 4-while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q95QUpHQ_9ru1S3hUMEU4atYouQpKkO_

exercicio 1
"""

nota=int(input("fale uma nota entre 0 a 10: "))

while nota <0:
  print("nota invalido")
  nota=int(input("fale uma nota entre 0 a 10"))
  if nota>10:
     print("nota invalido")
  nota=int(input("fale uma nota entre 0 a 10"))
print("NOTA VALIDA")

"""exercicio 1"""

while True:
  nota=int(input("fale uma nota entre 0 a 10: "))
  if nota > 10:
    print("valor invalidd")
  elif nota <0:
    print("valor invalido")
  else:
    print("valor valido")
    break

"""exercicio 2"""

total=0
cont= 0
numero=int(input("quantas notas voce quer? "))

while cont < numero:
  nota=float(input("fale uma nota: "))
  total+=nota
  cont+=1


media= total/numero
print(f"sua media é de {media:.2f}")

"""exercicio 3"""

import getpass
nome=(input("fale seu nome: "))
senha=getpass.getpass("digite sua senha: ")

while nome == senha:
  print("a senha nao pode ser igual a seu nome")
  senha=getpass.getpass("digite sua senha: ")

print("CADASTRO CONCLUIDO COM SUCESSO!")

"""exercicio 4"""

print("voce foi contratado em 1995")
salario1= 1000
ano=1995
porcentual=1.5


while ano <= 2025:
  total= salario1 * porcentual
  porcentual*=2
  ano+=1

print(f"seu salario atual é de {total:.2f}")

salario= int(input("qual é o seu salario? "))
ano=1995
porcentual=1.5

while ano <= 2025:
  total= salario * porcentual
  porcentual*=2
  ano+=1

print(f"seu salario atual é de {total:.2f}")

"""exercicio 5"""

nome=(input("qual é o seu nome? "))
while len(nome)<3:
  print("nome invalido,tente novamente ")
  nome=(input("qual é o seu nome? "))
print(f"o seu nome {nome} é valido")
while True:
  idade=int(input("fale sua idade: "))
  if idade > 150:
    print("idade invalida")
  elif idade <0:
    print("idade invalida")
  else:
    print("idade valida")
    break

salario=int(input("qual é o seu salario? "))
while salario<0:
  print("salario invalido,tente novamente ")
  salario=int(input("qual é o seu salario? "))
print(f"o seu salario de R${salario:.2f} é valido")


while True:
  sexo=(input("qual é o seu sexo? "))
  if sexo == "feminino":
    print("sexo valido")
    break
  elif sexo == "masculino":
    print("sexo valido")
    break
  else:
    print("sexo invalido, tente novamente: ")
    sexo=(input("qual é o seu sexo? "))

while True:
  civil=(input("qual é o seu estado civil: "))
  if civil=="solteiro":
   print("estado civil valido")
   break
  elif civil=="casado":
    print("estado civil valido")
    break
  elif civil=="viuvo":
    print("estado civil valido")
    break
  elif civil ==" divorciado":
   print("estado civil valido")
   break
  else:
    print("estado civil invalido, tente novamente ")
    civil=(input("qual é o seu estado civil"))

"""exercicio 6"""

populaçao_a=80000
populaçao_b=200000
porcentual_a=0.03
porcentual_b=0.015
ano=0
while populaçao_a < populaçao_b:
  populaçao_a+= populaçao_a * porcentual_a
  populaçao_b+= populaçao_b * porcentual_b
  ano+=1
print(f"precisa de {ano} anos para a população A ultrapassar a população B")

"""exercicio 7"""

numero=int(input("fale um numero: "))
f=1
i=1


while i<= numero:
  f*=i
  i+=1
print(f"o {numero} fatorado é : {f}")

"""exercicio 8"""

total=0
media=0
while True:
  numero=int(input("fale um numero ou digite 0 pra sair:"))
  if numero > 0:
    total+=numero
    media+=1
  elif numero<0:
    total+=numero
    media+=1
  else:
      break
resultado= (total/media)
print(f"a media é {resultado}")

"""exercicio 10"""

while True:
  print("Lojas Tabajara")
  total=0
  produto=1

  while True:
    preco=float(input(f"produto {produto}: R$"))
    if preco==0:
      break
    total+=preco
    produto+=1
  print(f"total R% {total:.2f}")
  dinheiro=float(input("dinheiro: R$ "))
  troco= dinheiro-total

  print(f"troco R$ {troco:.2f}")
  resposta= input("deseja realizar uma nova compra? ")
  if resposta == "nao":
    print("compras finalizadas! ")
    break

"""exercicio 11"""

print("-------Bem vindo ao mercadinho-------")
print("               cardapio:             ")
print("""
100 - Cachorro Quente - R$ 1,20
101 - Bauru Simples - R$ 1,30
102 - Bauru com ovo - R$ 1,50
103 - Hambúrguer - R$ 1,20
104 - Cheeseburguer - R$ 1,30
105 - Refrigerante - R$ 1,00
""")
total=0
while True:
 codigo=int(input("Qual é o codigo do produto que voce deseja? ou digite 0 pra sair "))
 if codigo==0:
  break
 if codigo == 100:
  preco= 1.20
  nome="cachorro quente"
 elif codigo==101:
  preco=1.30
  nome="bauro simples"
 elif codigo==102:
  preco=1.50
  nome="bauro com ovo"
 elif codigo ==103:
  preco=1.20
  nome= "hamburgue"
 elif codigo == 104:
  preco=1.30
  nome="cheeseburgue"
 elif codigo==105:
  preco=1.00
  nome="refrigerante"
 else:
  print("codigo invalido")
 quantida=int(input(f"quantos {nome} voce deseja? "))
 total_item=preco*quantida
 total+=total_item
 print(f"{quantida}x{nome}= R$ {total_item:.2f}")
print(f"total a pagar: R$ {total:.2f}")

"""exercicio 12"""

print("eleição")
print("fale o codigo do seu voto: ")
print("1 - jose")
print("2 - maria")
print("3 - joao")
print("4 -  ana")
print("5- voto nulo")
print("6 - voto em branco")
print("0 - encerrar votação")

voto1=0
voto2=0
voto3=0
voto4=0
nulo=0
branco=0
total=0

while True:
  codigo=int(input("fale o codigo do voto: "))
  if codigo==0:
    break
  if codigo ==1:
    voto1+=1
  elif codigo ==2:
    voto2+=1
  elif codigo==3:
    voto3+=1
  elif codigo==4:
    voto4+=1
  elif codigo==5:
    nulo+=1
  elif codigo==6:
    branco+=1
  else:
    print("tente novamente!")
  total+=1
if total>0:
  perc_nulo= (nulo/total) * 100
  perc_branco=(branco/total) *100
else:
  perc_nulo=0
  perc_branco=0

print(f"RESULTADO DA ELEIÇOES ")
print(f" jose: {voto1}")
print(f" maria : {voto2}")
print(f" joao: {voto3}")
print(f" ana: {voto4}")
print(f" nulo: {nulo}")
print(f" branco: {branco}")
print(f" porcentual de nulos: {perc_nulo}")
print(f" percentual branco: {perc_branco}")]

