# -*- coding: utf-8 -*-
"""lista de exercicio 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jOgF1g7AcwTytXpOvonLopEOyAK23TFR

exercicio 1
"""

total=0
maior=0
hora_maior = 0

for hora in range(1,7):
  visitantes=int(input(f"quantas visitantes passou na {hora}° ? "))
  total+=visitantes

  if visitantes>maior:
    maior = visitantes
    hora_maior = hora

print(f" a hora que teve mais visitas foi a {hora_maior }°hora com {maior} passoas  ")

print(f"hoje {total} pessoas visitaram o museu!")

"""exercicio 2"""

import getpass
for senha in range(8):
  digito=getpass.getpass("coloque sua senha do usuario: ")
  if len(digito)==8:
    print("senha correta")

  else:
    print("senha invalida")

"""exercico 3"""

falta=0

for produtos in range(1,11):
  quantidade=int(input(f"qual é a quantidade do produto {produtos}?"))
  if quantidade == 0:
    falta+=1

print(f" {falta} produtos que esta em falta")

produtos=[]

for mercadoria in range(1,11):
  produtos.append(int(input("informe a quantidade do produto",mercadoria)))

for estoque in range(lem(produtos)):
  if produtos[mercadoria] == 0:
    print(mercadoria)

"""exercicio 4"""

total=0
print("  A MEDIA NA NOSSA ESCOLA É 6 !")
for alunos in range(8):
  nota=int(input("qual é a sua nota: "))
  nota1=int(input("qual é a sua nota: "))
  media=((nota+nota1)/2)
  if media >=6:
    total+=1
    print(f"sua media é de {media} , vc esta aprovado")
  elif media >= 5:
    print(f"sua media é de {media} , vc esta de recuperação")
  else:
    print(f"sua media é de {media} , vc esta reprovado")
print(f"tem {total} alunos acima da media ")

"""exercico 5"""

for tabu in range(0,11):
  print( f"\ntabuada do {tabu}")
  for numeros in range(11):
   print(f"{tabu}x{numeros}= {tabu * numeros}")

"""exercicio 6"""

media=[]
for i in range(1,5):
  print(f"\n {i}° dia")
  soma=0
  for j in range(1,4):
    temp=float(input(f"digite a {j}° temparatura: "))
    soma+= temp
  media.append(soma/3)
for i in range(len(media)):
  if media[i]>30:
    print(f"\n o {i}° dia teve uma media maior qe 30°")

"""exercicio 7"""

for i in range(1,6):
  print("*" *(i))

numeros=[]
soma=0
for quantidade in range(1,6):
  soma=int(input(f"digite um numero "))
  numeros.append(soma)

print(f"a soma de todos os numeros é: {sum(numeros)}")

numeros =[]
pares=0
for i in range(10):
  num=int(input("fale um numero:"))
  numeros.append(num)
  if num % 2==0:
    pares+=1
print(f"voce digitou {pares} numeros pares")

nomes =[]
for i in range(5):
  nome=(input("fale um nome: "))
  nomes.append(nome)
print("nome na ordem inversa")

for nome in nomes[::-1]:
  print(nome)

valor =[]
maior=0
for valor1 in range(1,6):
  valor.append(int(input("digite um valor: ")))
  if valor > maior:
    maior=valor
  print(min(valor1))

maior=0
cadastro={}
for n in range(1,6):
  cadastro.append(input("\nqual é o seu nome? "))
  idade=(input("\nvoce tem mais de 18 anos? "))
  if idade == "sim":
    print(f"o {cadastro} é maior de idade. ")
    maior+=1
  elif idade == "não":
    print(f"o {cadastro} é menor de idade")
  else:
    print("nao entendi sua resposta")
print(f"TEM {maior} pessoas maior de idade")
print(f"T {cadastro} pessoas maior de idade")