# -*- coding: utf-8 -*-
"""lista de exercicio 5-while.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xzw1dOVtfiko_eSt49gQG_BUrCl4MR7I
"""

numero=int(input("fale um numero de 0 a 10 e tente acertar qual foi o numero escolido: "))
while numero != 5:
  print("numero errado, tente novamente:")
  numero=int(input("digite outro numero:"))
print("PARABÉNS VOCE ACERTOU")

import getpass

senha=getpass.getpass("fale uma senha de 4 digitos: ")
while senha != "1234":
  print("acesso negado, tente novamente! ")
  senha=getpass.getpass("fale uma senha de 4 digitos: ")
print("acesso liberado!")

contador= 1
numero=int(input("fale um numero: "))
while contador<=numero:
  print(contador)
  contador+=1

contador=0
numero=int(input("fale um numero: "))

while contador<10:
  contador+=1
  total=numero*contador
  print(f"{contador}x{numero}={total} ")

contador=0
while True:
  numero=int(input("fale um numero ou digite o para sair: "))
  contador+=numero
  if numero==0:
    break

print(f"a soma dos numeros que voce falou é {contador}")

maior=0

for numero in range(5):
  numero=int(input("fale um numero: "))
  if numero>maior:
    maior=numero
print(f"o maior numero é o {maior}")

menor=float("inf")

for numero in range(5):
  numero=int(input("fale um numero: "))
  if numero<menor:
    menor=numero
print(f"o menor numero é o {menor}")

# prompt: Peça 5 números e mostre qual foi o menor número digitado.

menor = float('inf') # Initialize with a very large number

for i in range(5):
  numero = int(input(f"Digite o {i+1}º número: "))
  if numero < menor:
    menor = numero

print(f"O menor número digitado é: {menor}")