# -*- coding: utf-8 -*-
"""lista de exercicios 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ursXUogfxEMknXeRHd4xOZvS361suUqZ

exercicio 1
"""

print(""" PRECISO CONTAR TIJOS, ME AJUDE""")

for tijolos in range(1,101):
  print(f"{tijolos} tijolos")

"""exercicio 2"""

print (""" ESTOU PINTANDO APENAS POSTES DE NUMERO PAR, CONSEGUE ME AJUDARA MOSTRAR QUAIS SÃO ELES""""")

for par in range(0,51,2):
  print(f"o poste {par} é par")

"""exercicio 3"""

print(" preciso saber quais são os participantes com os numeros impares")

for participante in range(1,101,2):
  print(f"o participante {participante} é impar, ele pode receber o kit especial")

"""exercicio 4"""

dinheiro=0
for vaquinha in range(5):
  valor=int(input("quanto voce contribuiu na vaquinha? "))
  dinheiro+= valor
media=(dinheiro/5)
total= (dinheiro)
print(f" o valor total é de R${total :.2f}")
print(f" a media é de R${media:.2f}")

"""exercico 5"""

print("BOLINHAS PARES:")
for par in range(0,10,2):
  print(f"- a bolinha {par} é par")

print("BOLINHAS IMPARES")
for impar in range(1,10,2):
  print(f"- a bolinha {impar} é impar")

"""EXERCICIO 6"""

print("TABUADA DO 10")
numero=int(input("fale um numero :"))

for tabuada in range(0,11):
  valor= (tabuada*numero)
  print(f"{tabuada} x {numero}= {valor}")

"""exercicio 7

"""

print(f"tabuada do 1 ao 10")
for numero in range(1,11):
  print(f"\ntabuada do {numero}:")
  for numero2 in range(1,11):
    print(f"{numero}x{numero2}= {numero*numero2}" )

"""exercicio 8"""

for numero in range(1,21):
  print(f"\n{numero}")
for numero in range(1,21):
  print(numero, end=" ")

"""exercicio 9"""

print("OS ID COM NUMERO IMPARES SÃO:")
for id in range(1,51,2):
  print(f"o {id} é impar")

"""exercicio 10"""

numero1=int(input("fale o valor de um numero: "))
numero2=int(input("fale o valor de um numero: "))

inicio=numero1
fim=numero2

for entre in range(inicio +1,fim):
  print(entre)

"""exercicio11"""

total=0
for vendas in range(5):
  valor=int(input("qual é o valor da venda?"))
  total+=valor
limite=54000
if total>limite:
  print(f"a loja faturou mais que  R${limite}")
  print(f"a loja faturou  R${total - limite}")
else:
  print(f"a loja não ultapassou a meta de {limite}")

"""exercicio 12"""

print("Robôs correndo:")
for robo in range(2, 21, 2):
    print(f"O robô número {robo} está correndo.")

"""exercicio 13"""

for numero in range(1000,2001):
  if numero % 11 ==2:
    print(f" O {numero} FOI SORTEADO")

"""exercicio 14"""

for numero in range(10,0,-1):
 print(numero)
print("LAMÇAR FOGUETE")

"""EXERCICIO 15"""

total= 0

for valor in range(1,31):
  moeda=int(input("qual é o valor da sua moeda "))
  total+= moeda

print(f"no total de 30 dias voce guardou {total}")

"""exercicio 16"""

maior=0
for bois in range(5):
  peso=int(input("qual é o peso desse boi? "))
  if peso>maior:
    maior=peso
print(f"o boi mais pesado é o que tem {maior}kg")

"""exercicio 17"""



# prompt: 17.Um funcionário teve aumento progressivo desde 1995. No primeiro ano,
# 1,5%, depois dobrando o percentual a cada ano. Calcule e mostre o
# salário até hoje.

salario_inicial = float(input("Informe o salário inicial do funcionário em 1995: "))
aumento_percentual = 0.015  # 1.5% em 1995
ano_atual = 2025

salario_atual = salario_inicial

print(f"Salário em 1995: R$ {salario_atual:.2f}")

for ano in range(1996, ano_atual + 1):
  aumento_percentual *= 2
  salario_atual += salario_atual * aumento_percentual
  print(f"Salário em {ano}: R$ {salario_atual:.2f}")

"""exercicio 18"""

estoque=0
for produto in range(1,11):
  produto1=int(input(f"quantos produtos {produto} voce tem? "))
  estoque+=produto1
print(f"voce tem {estoque} produtos no seu estoque")

"""exercico 19"""

mais=0
menos=0
for temperatura in range(1,8):
  temp=int(input(f"quantos graus esta no dia {temperatura}? "))
  if temp>mais:
    mais=temp

print(f"o dia mais quente teve {mais} graus")
if temp<menos:
    menos=temp
print(f"o dia mais frio teve {menos} graus")

# prompt: 19.Durante 7 dias, a cidade registrou temperaturas. Mostre a temperatura de
# cada dia, a média, a maior e a menor.

temperaturas = []
for dia in range(1, 8):
  temp = int(input(f"Quantos graus está no dia {dia}? "))
  temperaturas.append(temp)

media = sum(temperaturas) / len(temperaturas)
maior = max(temperaturas)
menor = min(temperaturas)

print("\nTemperaturas por dia:")
for i, temp in enumerate(temperaturas):
  print(f"Dia {i+1}: {temp} graus")

print(f"\nMédia da temperatura: {media:.2f} graus")
print(f"Maior temperatura registrada: {maior} graus")
print(f"Menor temperatura registrada: {menor} graus")

"""exercicio 20"""

# prompt: 20.Mostre os números de 1 até 100, mas substitua os múltiplos de 3 por
# "Fizz", os múltiplos de 5 por "Buzz" e os de ambos por "FizzBuzz".

print("\nExercício 20:")
for numero in range(1, 101):
  if numero % 3 == 0 and numero % 5 == 0:
    print("FizzBuzz")
  elif numero % 3 == 0:
    print("Fizz")
  elif numero % 5 == 0:
    print("Buzz")
  else:
    print(numero)