# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

exercicio 1
"""

x1 = 6+4*2
x2 = ( 4*9+5)
x3 = ((6+7)*9)
x4 = (15+20-30)
x5 = (15+20-30)
x6 = (6+5**2)
x9 = x1+x2+x3+x4+x5+x6
print(x9)

numero= 7
numero+=7
print(numero)

x = 8
x+=5
print(x)
x-=4
print(x)
x*=20
print(x)
x/=2
print(x)

nome= "biel"
x1= "legal"
x2= "Bonito"

print(f"qual é o seu nome? {nome} ele é muitio {x2} e ele é o homem mais {x2}")

x=2
x1=9
soma= x+x1
if soma < 10:
  print("a soma é menor que 10")
elif soma >=10:
  print(" a soma é maior que 10")

x= 8
x1=3

xresultado =x < x1
print(xresultado)
xresultado =x == x1
print(xresultado)
xresultado = x>x1
print(xresultado)
xresultado = x!= x1
print(xresultado)

idadelucas=int(input("qual é a idade de lucas?"))
idadecarol=int(input("qual é a idade de carol?"))

if(idadelucas >=18 and idadecarol >=18):
  print("os dois é maior de idade")
elif(idadelucas<=18 and idadecarol <=18):
  print('os dois sao menores de idade!')
elif(idadelucas>=18 or idadecarol <=18):
  print('lucas é maior de idade e carol nao')
elif(idadelucas<=18 or idadecarol >=18):
  print('carol é maior de idade e lucas nao')

carlos="botafogo"
luciano= "flamengo"
fabricia= "botafogo"
print(carlos is not luciano)

x ="botafogo"
x1 = "flamengo"
x3 = "botafogo"

resultado = x is x3
print( resultado)
resultado = x is not x3
print(resultado)
resultado = x1 is x3
print(resultado)
resultado = x1 is not x3
print(resultado)

frutas = ["banana","laranja","uva","ameixas"]

fruta1= "ameixas"
fruta2= "melancia"

print(fruta1 in frutas)
print(fruta2 in frutas)

x = 4
x1= 9
x2 = 5

resultado= (((2+5)*3)+x+5)<x1
print(resultado)
resultado= (((2+5)+3)+(x+5<x1)==(x==6+x2*2))
print(resultado)
resultado= (((3*6)+x-3)<x2)
print(resultado)
resultado= (((7*8)>(x+4>x1)<(x!=2+x2*9)))
print(resultado)

nota1= float(input("digite uma nota?"))
nota2= float(input("digite outra nota?"))
media= (nota1+nota2)/2

if media>=7:
  print("voce passou de ano")
elif media<=7:
  print("voce não passou de ano")

numero= int(input("fale um numero?"))

if numero>30:
  print("esse numero é menor que o numero 30")
elif numero<30:
  print("esse numero e maior que o numero 30!")

nota1= float(input("digite uma nota?"))
nota2= float(input("digite outra nota?"))
media= (nota1+nota2)/2

if media<=7:
  print(f"voce esta reprovado!! Sua media é{media}")
elif media>= 5:
  print(f"o aluno esta de recuperação!! Sua media é{media}")
else:
  print(f"parabens, vc esta aprovado!! Sua media é {media} Some daqui!!")

a= int(input("coloque um numero de 0 a 100:"))
if a>50:
  print("o numero",a,"é maior que 50")
elif a==50:
  prit("o numero informado é igual a 50")
else:
  print("o numero" ,a,"é menor que 50")

alimentos=(input("qual comida voce desja comer hoje?"))

if alimentos=="arroz":
  print("vmas jantar", alimentos)
elif alimentos =="macarrão":
  print("vms jantar", alimentos)
else:
  print("hj nao tem na lista")