# -*- coding: utf-8 -*-
"""treinando codigos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TE-c29x9RCIgynzpA5ZAwzGyM6ou0Leu
"""

print("""
Estamos verificando alguns numeros
""")
numero1=int(input("Fale o valor de um numero: "))
numero2=int(input("Fale o valor de um numero: "))
soma=(numero1+numero2)
if soma is 15 :
  print(f"o numero {soma} é igual a  15")
elif soma is not 15 and soma>15:
  print(f"O numero {soma} não é igual a 15 e é maior")
elif soma is not 15 and soma<15:
  print(f"O numero {soma} não é igual a 15 e é menor")

print(""" ESTAMOS QUERENDO SABER O QUE CADA NUMERO É:
""")
numero10=int(input(" me fala um numero por favor:"))
numero11=int(input(" me fala um numero por favor:"))
soma=(numero10*numero11)
positivo= soma>0
neutro= soma==0
negativo= soma<0
if soma == 0:
  print(f"o numero {soma} é neutro")
elif soma > 0:
  print(f"o numero {soma} é positivo")
else:
  print(f"o numero {soma} é negativo")

print("agora vou explicar o que é cada numero:")

if soma == neutro:
  print("um numero neutro é quando ele é o numero 0")
elif soma == positivo:
  print("um numero positivo é quando ele é maior que o numero 0 e isso faz ele ser um numero positivo ")
else:
  print('o numero negativo é quando é abaixo de 0')

idanna= int(input("quantos anos voce tem Anna? "))
idfernando=int(input("quantos anos voce tem fernando? "))

if idanna<18 and idfernando>18:
  print(f"Anna voce tem {idanna}, voce é menor de idade e fernando é maior de idade")
elif idanna>18 and idfernando<18:
  print(f"Anna é maior de idade e fernando voce tem {idfernando},voce é menor de idade")

import getpass
senha1=int(inout("qual é sua senha? "))
senha="1234"

if senha1 min senha:
  pr