# -*- coding: utf-8 -*-
"""treinando match  e case

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5khK7HapL4lXorBcgA7Xu4yaEPbImrK
"""

while True:
 dia= int(input("fale um numero de 1 a 7: "))
 match dia:
  case 1:
    print("hoje é domingo ")
  case 2:
    print("hoje é segunda ")
  case 3:
    print("hoje é terça ")
  case 4:
    print("hoje é quarta ")
  case 5:
    print("hoje é quinta ")
  case 6:
    print("hoje é sexta ")
  case 7:
    print("hoje é sabado ")
  case _:
    break

print("""
eschole alguma das opções:
1- cadastrar usuario
2-excluir usuario
3-listar usuario
""")

opcao=int(input("digite alguma opção: "))
match opcao:
  case 1:
    print("usuario cadastrado com sucesso")
  case 2:
    print("usuario excluido com sucesso")
  case 3:
    print("lista do usuario: ")
  case _:
    print("opção invalida")

nota=int(input("fale uma nota de 0 a 10: "))
match nota:
  case 10|9:
    print("conceito A")
    print("PARABÉNS! ")
  case 8|7:
    print("conceito B ")
  case 6|5:
    print("conceito C")
  case 1|2|3|4:
    print("conceito D")
  case _:
    print("nota invalida")

calculadora=float(input("digite um numero: "))
calculadora1=float(input("digite outro numero: "))
operacao=(input("digite qual é operação que deseja realizar (*,+,-,/)"))

match operacao:
  case "*":
    print(f"{calculadora:.0f}*{calculadora1:.0f}= {calculadora1*calculadora}")
  case "+":
    print(f"{calculadora:.0f}+{calculadora1:.0f}= {calculadora1+calculadora:.0f}")
  case "-":
    print(f"{calculadora:.0f}-{calculadora1:.0f}= {calculadora1-calculadora:.0f}")
  case "/":
    print(f"{calculadora:.0f}/{calculadora1:.0f}= {calculadora1/calculadora:.0f}")
  case _:
    print("valor invalido")